GET http://192.168.5.7:10000/
Accept: application/json

###
POST http://192.168.5.7:10000/
Accept: application/json
Content-Type: application/json

{
  "appVersion": "v0.8.1",
  "extraInfo": {
    "nodeCount": "1",
    "cpuCount": "72",
    "memorySize": "32Gi",
    "clusterUID": "8ea1da9b-ba5c-4205-be64-f93b0797e81a"
  }
}


